openapi: 3.0.0
info:
  title: PLANT APP API
  version: 1.0.0
servers:
  - url: https://plantapp-2mp9.onrender.com/api/v1
    variables: {}

paths:
  /auth/login:
    post:
      tags:
        - Auth
      summary: Login user
      operationId: LoginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUserRequest"
            example:
              email: mama@gmail.com
              password: shewareg
      responses:
        "200":
          description: Logged in
          content:
            application/json:
              example:
                {
                  "user":
                    { "name": "Mama", "userId": "68958ea9316675518a96b222" },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk1OGVhOTMxNjY3NTUxOGE5NmI0MzkiLCJuYW1lIjoiU3R1IiwiaWF0IjoxNzU1MDQ2Mjc1LCJleHAiOjE3NTc2MzgyNzV9.-WmPybA09SJ0I5feFY7rgFlaEPVBBrC-aomp1QwrVBv",
                }
      security: []

  /auth/register:
    post:
      tags:
        - Auth
      summary: Register user
      operationId: RegisterUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterUserRequest"
            example:
              name: elinatal
              email: baby@gmail.com
              password: timotios
      responses:
        "201":
          description: Registered
          content:
            application/json:
              example:
                {
                  "user":
                    {
                      "name": "elinatal",
                      "userId": "68958ea9316675518a96b234",
                    },
                  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODk1OGVhOTMxNjY3NTUxOGE5NmI0MzkiLCJuYW1lIjoiU3R1IiwiaWF0IjoxNzU1MDQ2Mjc1LCJleHAiOjE3NTc2MzgyNzV9.-WmPybA09SJ0I5feFY7rgFlaEPVBBrC-aomp1QwrfEv",
                }
      security: []

      # post:
      # tags:
      #   - Identify Plants
      # summary: Identify plant by image
      # operationId: identifyPlants
      # parameters: []
      # requestBody:
      #   description: ""
      #   content:
      #     multipart/form-data:
      #       schema:
      #         type: object
      #         $ref: "#/components/schemas/IdentifyPlantsRequest"
      #         properties:
      #           images:
      #             type: string
      #             format: binary
      #   required: true
      # responses:
      #   "200":

  /plants:
    post:
      tags:
        - Plants
      summary: Create plant entry
      operationId: CreatePlantEntry
      parameters: []
      requestBody:
        description: ""
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/CreatePlantEntryRequest"
        required: true
      responses:
        "201":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "plant":
                    {
                      "name": "palm tree",
                      "imageURL": "https://storage.googleapis.com/plant-app-4a554.firebasestorage.app/plants/1756775676041-palm-tree.jpeg",
                      "notes": "It has coconuts",
                      "location": "The beach",
                      "createdBy": "68958ea9316675518a96b420",
                      "_id": "689bd41309dc34a1f4082111",
                      "createdAt": "2025-08-12T23:53:55.317Z",
                      "updatedAt": "2025-08-12T23:53:55.317Z",
                      "__v": 0,
                    },
                }
          headers: {}
      deprecated: false

    get:
      tags:
        - Plants
      summary: Get all plant entries
      operationId: GetAllPlantEntries
      parameters: []
      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "plants":
                    [
                      {
                        "_id": "68979fc17f6eddd77c76db3s",
                        "name": "rose",
                        "createdBy": "68958ea9316675518a96b421",
                        "imageURL": "https://storage.googleapis.com/plant-app-4a554.firebasestorage.app/plants/1756666481871-cactus.jpg",
                        "notes": "This rose is beautiful!",
                        "location": "222 N Smith Ln",
                        "createdAt": "2025-08-09T19:21:37.403Z",
                        "updatedAt": "2025-08-09T19:21:37.403Z",
                        "__v": 0,
                      },
                      {
                        "_id": "6897a1d5b6dc952f78612efr",
                        "name": "cactus",
                        "imageURL": "www.crazy-cactus-img.com",
                        "notes": "This was growing in my backyard",
                        "location": "my backyard",
                        "createdBy": "68958ea9316675518a96b476",
                        "createdAt": "2025-08-09T19:30:29.924Z",
                        "updatedAt": "2025-08-09T19:30:29.924Z",
                        "__v": 0,
                      },
                    ],
                  "count": 2,
                }
          headers: {}
      deprecated: false

  /plants/{plantID}:
    parameters:
      - in: path
        name: plantID
        schema:
          type: string
          example: 68991aa9444dc94a77ead824
        required: true
        description: The plant ID

    get:
      tags:
        - Plants
      summary: Get single plant entry
      operationId: GetSinglePlantEntry
      parameters: []
      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "plant":
                    {
                      "_id": "68991aa9444dc94a77ead848",
                      "name": "oak tree",
                      "imageURL": "www.oaktrees.net",
                      "notes": "Massive oak tree I saw!",
                      "location": "near the forest south of town",
                      "createdBy": "68958ea9316675518a96b439",
                      "createdAt": "2025-08-10T22:18:17.679Z",
                      "updatedAt": "2025-08-10T23:42:03.742Z",
                      "__v": 0,
                    },
                }
          headers: {}
      deprecated: false

    patch:
      tags:
        - Plants
      summary: Update plant entry
      operationId: UpdatePlantEntry
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePlantEntryRequest"
            example:
              name: "oak tree"
              imageURL: "www.oaktrees.net"
              notes: "Massive oak tree I saw!"
              location: "near the forest south of town"
        required: true
      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "plant":
                    {
                      "_id": "68991aa9444dc94a77ead848",
                      "name": "oak tree",
                      "imageURL": "www.oaktrees.net",
                      "notes": "Massive oak tree I saw!",
                      "location": "near the forest south of town",
                      "createdBy": "68958ea9316675518a96b439",
                      "createdAt": "2025-08-10T22:18:17.679Z",
                      "updatedAt": "2025-08-13T00:28:09.856Z",
                      "__v": 0,
                    },
                }
          headers: {}
      deprecated: false

    delete:
      tags:
        - Plants
      summary: Delete plant entry
      operationId: DeleteExercise
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              example: { msg: "The entry was successfully deleted" }
          headers: {}
      deprecated: false

  /identifyPlants:
    post:
      tags:
        - Identify Plants
      summary: Identify plant by image
      operationId: identifyPlants
      parameters: []
      requestBody:
        description: ""
        content:
          multipart/form-data:
            schema:
              type: object
              $ref: "#/components/schemas/IdentifyPlantsRequest"
              properties:
                images:
                  type: string
                  format: binary
        required: true
      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "data":
                    [
                      {
                        "id": 2498,
                        "common_name": "Venus fly trap",
                        "scientific_name": ["Dionaea muscipula"],
                        "default_image":
                          {
                            "license": 45,
                            "license_name": "Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)",
                            "license_url": "https://creativecommons.org/licenses/by-sa/3.0/deed.en",
                            "original_url": "https://perenual.com/storage/species_image/2498_dionaea_muscipula/og/2560px-Dionaea_muscipula2C_exhibition_in_Botanical_garden_Brno.jpg",
                            "regular_url": "https://perenual.com/storage/species_image/2498_dionaea_muscipula/regular/2560px-Dionaea_muscipula2C_exhibition_in_Botanical_garden_Brno.jpg",
                            "medium_url": "https://perenual.com/storage/species_image/2498_dionaea_muscipula/medium/2560px-Dionaea_muscipula2C_exhibition_in_Botanical_garden_Brno.jpg",
                            "small_url": "https://perenual.com/storage/species_image/2498_dionaea_muscipula/small/2560px-Dionaea_muscipula2C_exhibition_in_Botanical_garden_Brno.jpg",
                            "thumbnail": "https://perenual.com/storage/species_image/2498_dionaea_muscipula/thumbnail/2560px-Dionaea_muscipula2C_exhibition_in_Botanical_garden_Brno.jpg",
                          },
                      },
                      {
                        "id": 2499,
                        "common_name": "Venus fly trap",
                        "scientific_name": ["Dionaea muscipula 'Akai Ryu'"],
                        "default_image":
                          {
                            "license": 6,
                            "license_name": "Attribution-NoDerivs License",
                            "license_url": "https://creativecommons.org/licenses/by-nd/2.0/",
                            "original_url": "https://perenual.com/storage/species_image/2499_dionaea_muscipula_akai_ryu/og/5638466264_af7c4be36f_b.jpg",
                          },
                      },
                    ],
                  "total": 2,
                }
          headers: {}
      deprecated: false

    get:
      tags:
        - Identify Plants
      summary: Get all plants by name
      operationId: GetAllPlantsByName
      parameters:
        - in: query
          name: name
          required: true
          schema:
            type: string
            example: pine
          description: The name of the plant to search for

      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "data":
                    [
                      {
                        "id": 7,
                        "common_name": "Alpine Fir",
                        "scientific_name": ["Abies lasiocarpa"],
                        "default_image":
                          {
                            "license": 5,
                            "license_name": "Attribution-ShareAlike License",
                            "license_url": "https://creativecommons.org/licenses/by-sa/2.0/",
                            "original_url": "https://perenual.com/storage/species_image/7_abies_lasiocarpa/og/51002756843_74fae3c2fa_b.jpg",
                            "regular_url": "https://perenual.com/storage/species_image/7_abies_lasiocarpa/regular/51002756843_74fae3c2fa_b.jpg",
                            "medium_url": "https://perenual.com/storage/species_image/7_abies_lasiocarpa/medium/51002756843_74fae3c2fa_b.jpg",
                            "small_url": "https://perenual.com/storage/species_image/7_abies_lasiocarpa/small/51002756843_74fae3c2fa_b.jpg",
                            "thumbnail": "https://perenual.com/storage/species_image/7_abies_lasiocarpa/thumbnail/51002756843_74fae3c2fa_b.jpg",
                          },
                      },
                      {
                        "id": 82,
                        "common_name": "Nishiki Gawa Japanese Maple*",
                        "scientific_name": ["Acer palmatum 'Nishiki Gawa'"],
                        "default_image":
                          {
                            "license": 451,
                            "license_name": "CC0 1.0 Universal (CC0 1.0) Public Domain Dedication",
                            "license_url": "https://creativecommons.org/publicdomain/zero/1.0/",
                            "original_url": "https://perenual.com/storage/species_image/82_acer_palmatum_nishiki_gawa/og/pexels-photo-4977537.jpg",
                            "regular_url": "https://perenual.com/storage/species_image/82_acer_palmatum_nishiki_gawa/regular/pexels-photo-4977537.jpg",
                            "medium_url": "https://perenual.com/storage/species_image/82_acer_palmatum_nishiki_gawa/medium/pexels-photo-4977537.jpg",
                            "small_url": "https://perenual.com/storage/species_image/82_acer_palmatum_nishiki_gawa/small/pexels-photo-4977537.jpg",
                            "thumbnail": "https://perenual.com/storage/species_image/82_acer_palmatum_nishiki_gawa/thumbnail/pexels-photo-4977537.jpg",
                          },
                      },
                    ],
                  "total": 2,
                }
          headers: {}
      deprecated: false

  /identifyPlants/{plantID}:
    parameters:
      - in: path
        name: plantID
        schema:
          type: string
          example: 2230
        required: true
        description: The plant ID

    get:
      tags:
        - Identify Plants
      summary: Get single plant data
      operationId: identifySinglePlant
      parameters: []
      responses:
        "200":
          description: "Successful Response"
          content:
            application/json:
              example:
                {
                  "data":
                    {
                      "id": 2230,
                      "common_name": "crocus",
                      "scientific_name": ["Crocus luteus 'Golden Yellow'"],
                      "origin":
                        [
                          "Turkey",
                          "Greece",
                          "Bulgaria",
                          "Albania",
                          "Macedonia",
                          "Serbia",
                          "Montenegro",
                          "Bosnia and Herzegovina",
                          "Croatia",
                        ],
                      "hardiness_zones": { "min": "3", "max": "8" },
                      "hardiness_location":
                        {
                          "full_url": "https://perenual.com/api/hardiness-map?species_id=2230&size=og&key=sk-7wRB68a4e4efc60fe11920",
                          "full_iframe": "<iframe frameborder=0 scrolling=yes seamless=seamless width=1000 height=550 style='margin:auto;' src='https://perenual.com/api/hardiness-map?species_id=2230&size=og&key=sk-7wRB68a4e4efc60fe11920'></iframe>",
                        },
                      "description": "Crocus luteus 'Golden Yellow' is truly an amazing flower. Its vibrant sunny yellow petals are a sight to behold! They stand atop thin green stems and offer a cheerful splash of color to any garden setting. As a spring-blooming perennial, it's hardy in most climates, and its spectacular display will reappear year after year. The lovely, aromatic blooms also attract bees and other pollinators, making it an excellent choice for butterfly gardens. Not a fan of mowing the lawn? Planting Crocus luteus 'Golden Yellow' in large clumps will provide a beautiful, low-maintenance, natural alternative and can even resist light foot traffic!",
                      "default_image":
                        {
                          "license": 45,
                          "license_name": "Attribution-ShareAlike 3.0 Unported (CC BY-SA 3.0)",
                          "license_url": "https://creativecommons.org/licenses/by-sa/3.0/deed.en",
                          "original_url": "https://perenual.com/storage/species_image/2230_crocus_luteus_golden_yellow/og/Crocus_ancyrensis002.jpg",
                          "regular_url": "https://perenual.com/storage/species_image/2230_crocus_luteus_golden_yellow/regular/Crocus_ancyrensis002.jpg",
                          "medium_url": "https://perenual.com/storage/species_image/2230_crocus_luteus_golden_yellow/medium/Crocus_ancyrensis002.jpg",
                          "small_url": "https://perenual.com/storage/species_image/2230_crocus_luteus_golden_yellow/small/Crocus_ancyrensis002.jpg",
                          "thumbnail": "https://perenual.com/storage/species_image/2230_crocus_luteus_golden_yellow/thumbnail/Crocus_ancyrensis002.jpg",
                        },
                      "cycle": "Perennial",
                      "sunlight": ["Full sun", "part shade"],
                      "growth_rate": "Low",
                      "care_level": "Moderate",
                      "watering": "Average",
                      "maintenance": "Low",
                    },
                }
          headers: {}
      deprecated: false

components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest
      required:
        - name
        - email
        - password
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
      example:
        name: bob
        email: bob@gmail.com
        password: secret

    LoginUserRequest:
      title: LoginUserRequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: susan@gmail.com
        password: secret

    CreatePlantEntryRequest:
      title: CreatePlantEntryRequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
        location:
          type: string
        notes:
          type: string
        file:
          type: string
          format: binary

    UpdatePlantEntryRequest:
      title: UpdatePlantEntryRequest
      type: object
      properties:
        name:
          type: string
        imageURL:
          type: string
        notes:
          type: string
        location:
          type: string
      example:
        name: oak tree
        imageURL: www.plant-life.com
        notes: Massive oak tree I saw!
        location: 231 Easy Street

    IdentifyPlantsRequest:
      title: IdentifyPlantsRequest
      type: object
      properties:
        image:
          type: string
          format: binary

  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer

security:
  - httpBearer: []

tags:
  - name: Auth
    description: User authentication with email & password
  - name: Plants
    description: Logged in user operation for creating and storing plant data
